---


- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  - name: install epel-release
    tags: epel-release
    dnf:
      name:
        - epel-release
      state: present
        
  - name: install apache2 package CentOS
    tags: httpd,centos
    package:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Copy index to webserver
    tags: httpd,centos
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644    

  - name: Start Apache
    service:
      name: httpd
      state: started
      enabled: yes

- hosts: db_servers
  become: true
  tasks:

  - name: install MariaDB package Ubuntu
    tags: ubuntu,mariadb,db
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package Ubuntu
    tags: ubuntu,samba
    apt:
      name:
        - samba
      state: latest
    when: ansible_distribution == "Ubuntu"




