---


- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (Rocky)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Rocky"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: create NOPASS ansible user
    tags: always
    user:
      name: hammer
      groups: root

  - name: add ssh key for hammer
    tags: always
    authorized_key:
      user: hammer
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCmvDTyqDY6DedYHX6lRzMyZ7D5a6CK73Q5tUJEO/5yTsbXWQD9e3hVbf3mfsOGjg+V5vJYu6nb1i5lK1jh3aw80jGcHkxDziVACIcNWDIFo/KJdYTkqgY2ocyoaj6D8aaD9ZI2vuazRT7fwhj7jP96+rKjQEIOzQur7zHQL+rriYDamf9zGDQnhl9N7McLBTNnTgBl9xWXtCn93KncrEBvxzlemARl8kc9Ihz0PRUQmMoxbne8ZVqxUzMfacZlN/XXllvEFlmOlpQLwNVvUSex9GgCT9g4F5m+Bie9Zgb2hEiqlCRDUqhqtsjpQLU/G1QAiTdo+3n1pSYvzwFqmtCN/x7c4X7P8QmctQStU0zc8MtGitezsvaEOyMu3UKJqRMoR/lhvt5OKn3iBPL/pu63nxhKo/RyTKVXLBZ57XvOAzux3tpIre/M+oC3uJa54mctT9S/xXhI4FAqNIuMRXKq2iYAItlOE5Fp0zz+H8IwA0s5wim2Ta4zEs71cE4Gq/KGmuEj3n65vmgX9D4WjehHdMOr4lBa2loj5hr7lWBeYd/cBpw0Ew4zB/0+xGacwVgl2zzJN4AVYFxRFDwaZ36PiVhYjzZkykSSvAVIuAx4Y4a45hH3AzoYBrgiAKxykYmHRJY00qixMUVYmWDtbsnfc7EYAPboJ7AyhxdIdbTyTw== ansible"

  - name: add sudoers file
    tags: always
    copy:
      src: sudoer_hammer
      dest: /etc/sudoers.d/hammer
      owner: root
      group: root
      mode: 0440

- hosts: web_servers
  become: true
  tasks:
  - name: install epel-release
    tags: epel-release
    dnf:
      name:
        - epel-release
      state: present
        
  - name: install apache2 package (Rocky)
    tags: httpd,rocky
    package:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Rocky"

  - name: change email add for admin
    tags: apache,rocky,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "Rocky"
    register: httpd

  - name: restart httpd (Rocky)
    tags: rocky,apache,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: Copy index to webserver
    tags: httpd,rocky
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644    

  - name: Start Apache
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Rocky"

- hosts: db_servers
  become: true
  tasks:

  - name: install MariaDB package Ubuntu
    tags: ubuntu,mariadb,db
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package Ubuntu
    tags: ubuntu,samba
    apt:
      name:
        - samba
      state: latest
    when: ansible_distribution == "Ubuntu"




